//register
POST http://localhost:5152/api/Account/login HTTP/1.1
Content-Type: application/json

{
  "userName": "string",
  "password": "string",
  "email": "string"
}

//login
###
POST http://localhost:5152/api/Account/login HTTP/1.1
Content-Type: application/json

{
    "userName": "string",
    "password": "string"
}

//get current user
###
GET http://localhost:5152/api/Account/currentUser HTTP/1.1
Authorization: Bearer <Token>